"""
data_io.py
==========
Loading (or synthesising) the two model inputs and preparing the temporal
tensors consumed by the pipeline.

Inputs described by the project spec
------------------------------------
1. Core causal subgraph (Pickle dict):
       {'graph': ndarray[N,N,tau_max+1] of '-->'/'' ,
        'val_matrix': ndarray[N,N,tau_max+1] float,
        'meta': {...}}
2. Intent graph (.npz):
       edges_list    : object array [n_show] of int[|E|,2]
       strength_list : object array [n_show] of float[|E|]
       delta_list    : float[n_show]

If the files are not supplied on disk this module synthesises statistically
faithful stand-ins (same dtypes / shapes / semantics) so the full pipeline is
runnable end-to-end.  The synthetic node time-series X is generated by a linear
diffusion process on the causal skeleton, which gives the training objective
genuine, learnable structure.
"""

from __future__ import annotations

import os
import pickle

import numpy as np


# --------------------------------------------------------------------------- #
#  Causal subgraph                                                             #
# --------------------------------------------------------------------------- #
def _synth_causal(cfg, rng):
    """Create a causal .pkl-equivalent dict with a sparse directed skeleton."""
    N, T = cfg.N, cfg.tau_max + 1
    graph = np.full((N, N, T), "", dtype=object)
    val = np.zeros((N, N, T), dtype=float)

    # scale-free-ish out-degree: a few hubs drive many targets
    hub_prob = rng.pareto(2.0, size=N)
    hub_prob = hub_prob / hub_prob.sum()
    n_edges = int(0.04 * N * N)                      # ~4 % density
    for _ in range(n_edges):
        i = rng.choice(N, p=hub_prob)               # source (hub-biased)
        j = rng.integers(N)
        if i == j:
            continue
        lag = rng.integers(0, T)
        graph[j, i, lag] = "-->"                     # convention: [target, source, lag]
        val[j, i, lag] = rng.normal(0.0, 0.6)

    top_ratio = 0.30
    # node importance = weighted in+out degree
    deg = (np.abs(val).sum(axis=(1, 2)) + np.abs(val).sum(axis=(0, 2)))
    k = int(top_ratio * N)
    top_nodes = np.argsort(-deg)[:k].tolist()
    meta = {
        "mask_threshold": 0.5,
        "selected_edges_count": int((graph == "-->").sum()),
        "total_edges_count": int((graph == "-->").sum()),
        "top_nodes": top_nodes,
        "top_nodes_count": k,
        "top_ratio": top_ratio,
        "node_score_mode": "inout",
        "edge_keep_mode": "or",
        "node_scores": deg,
    }
    return {"graph": graph, "val_matrix": val, "meta": meta}


def load_causal(cfg, rng):
    if cfg.causal_pkl and os.path.exists(cfg.causal_pkl):
        with open(cfg.causal_pkl, "rb") as f:
            d = pickle.load(f)
        return d, False
    return _synth_causal(cfg, rng), True


def causal_adjacency(causal, N):
    """
    Collapse the [N,N,tau_max+1] causal tensor into a single weighted adjacency
    A_C[i,j] = strength of causal edge j -> i (aggregated over lags).
    Returned as [N, N] with A_C[i, j] meaning i receives from j.
    """
    graph = causal["graph"]
    val = np.abs(np.asarray(causal["val_matrix"], dtype=float))
    mask = (graph == "-->").astype(float)
    A = (val * mask).sum(axis=2)                     # [target, source]
    return A


# --------------------------------------------------------------------------- #
#  Intent graphs                                                              #
# --------------------------------------------------------------------------- #
def _synth_intent(cfg, causal, rng):
    """
    Create an intent .npz-equivalent: a slowly drifting subset of causal edges
    is activated per time step, with strengths and a q=0.90 quantile delta.
    """
    N = cfg.N
    graph = causal["graph"]
    val = np.abs(np.asarray(causal["val_matrix"], dtype=float))
    tgt, src, _ = np.where(graph == "-->")
    cand = np.stack([src, tgt], axis=1)              # candidate directed edges (src, dst)
    cand = np.unique(cand, axis=0)
    Ecand = len(cand)

    # base strength per candidate edge from causal magnitude
    base = np.array([val[d, s].sum() for s, d in cand]) + 0.05
    base = base / (base.max() + 1e-9)

    edges_list = np.empty(cfg.n_show, dtype=object)
    strength_list = np.empty(cfg.n_show, dtype=object)
    delta_list = np.zeros(cfg.n_show, dtype=float)

    phase = rng.uniform(0, 2 * np.pi, size=Ecand)
    freq = rng.uniform(0.02, 0.12, size=Ecand)

    for t in range(cfg.n_show):
        # time-varying score: smooth oscillation + noise, gated by base strength
        wave = 0.5 * (1 + np.sin(2 * np.pi * freq * t + phase))
        s_vec = base * wave + 0.05 * rng.standard_normal(Ecand)
        s_vec = np.clip(s_vec, 1e-3, None)
        delta = np.quantile(s_vec, 0.90)             # q = 0.90 activation threshold
        keep = s_vec >= delta
        edges_list[t] = cand[keep].astype(int)
        strength_list[t] = s_vec[keep].astype(float)
        delta_list[t] = float(delta)

    return {
        "edges_list": edges_list,
        "strength_list": strength_list,
        "delta_list": delta_list,
    }


def load_intent(cfg, causal, rng):
    if cfg.intent_npz and os.path.exists(cfg.intent_npz):
        d = np.load(cfg.intent_npz, allow_pickle=True)
        return {
            "edges_list": d["edges_list"],
            "strength_list": d["strength_list"],
            "delta_list": d["delta_list"],
        }, False
    return _synth_intent(cfg, causal, rng), True


def intent_adjacencies(intent, N, n_show):
    """Reconstruct a [n_show, N, N] weighted intent adjacency stack A_I^t[i,j]."""
    edges = intent["edges_list"]
    strengths = intent["strength_list"]
    A = np.zeros((n_show, N, N), dtype=float)
    T = min(n_show, len(edges))
    for t in range(T):
        e = np.asarray(edges[t], dtype=int).reshape(-1, 2)
        s = np.asarray(strengths[t], dtype=float).reshape(-1)
        for (src, dst), w in zip(e, s):
            A[t, dst, src] += w                      # [dst, src] to match causal convention
    return A


# --------------------------------------------------------------------------- #
#  Node time-series X                                                         #
# --------------------------------------------------------------------------- #
def synth_node_features(cfg, A_C, rng):
    """
    Generate node states X in R^[n_show, N, F_in] via linear diffusion on the
    causal skeleton so that features carry structure the model can predict.
        x_{t} = alpha * A_hat @ x_{t-1} + noise
    """
    N, F = cfg.N, cfg.F_in
    A = A_C.copy()
    deg = A.sum(axis=1, keepdims=True) + 1e-9
    A_hat = A / deg                                  # row-normalised
    X = np.zeros((cfg.n_show, N, F))
    X[0] = rng.standard_normal((N, F))
    alpha = 0.7
    for t in range(1, cfg.n_show):
        X[t] = alpha * (A_hat @ X[t - 1]) + 0.3 * rng.standard_normal((N, F))
    # standardise per feature
    X = (X - X.mean(axis=(0, 1), keepdims=True)) / (X.std(axis=(0, 1), keepdims=True) + 1e-9)
    return X


# --------------------------------------------------------------------------- #
#  Normalisation utility                                                       #
# --------------------------------------------------------------------------- #
def normalize_adj(A):
    """Symmetric-ish min-max normalisation to [0,1] used for \tilde A."""
    m = A.max()
    if m <= 0:
        return A
    return A / m


def row_normalize(A):
    """Row-normalise a weighted adjacency for GNN aggregation (adds self-loop)."""
    A = A + np.eye(A.shape[0])
    d = A.sum(axis=1, keepdims=True) + 1e-9
    return A / d
